spring.application.name=springboot-file-storage
spring.datasource.url=jdbc:mariadb://localhost:3306/file_storage?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true
# Frontend url
app.frontend.url=http://localhost:5173
# jwt
security.jwt.secret-key=your_key
security.jwt.expiration-time=3600000
# Deletion file after how many weeks
spring.files.delete.after.weeks=2
# Does the system allow users to manually sign up?
spring.registration.can.register=true
